create table CLIENTE(
	ID IDENTITY NOT NULL PRIMARY KEY,
	NOMBRE VARCHAR(50),
	APELLIDO1 VARCHAR(50),
	APELLIDO2 VARCHAR(50)

);

create table DIRECCION(
	ID IDENTITY NOT NULL PRIMARY KEY,
	CALLE VARCHAR(100),
	BLOQUE VARCHAR(10),
	PUERTA VARCHAR(10),
	ID_CLIENTE INTEGER

);

ALTER TABLE DIRECCION ADD FOREIGN KEY ( ID_CLIENTE ) REFERENCES CLIENTE( ID ) ;